commands:

  - type: sync
    repo: 'https://github.com/tarjoilija/zgen'
    dst:  "<%= get_var! :'zsh.custom_dir', type: :directory %>/plugins/zgen"
    only: f?zsh

elems:

  - src:  ^(zshrc)$
    dst:  "<%= get_var! :'zsh.zshrc_path', type: :file %>"
    only: f?zsh

  - src:  ^(zshenv)$
    dst:  "<%= get_var! :'zsh.zshenv_path', type: :file %>"
    only: f?zsh

  - src:  ^(zlogin)$
    dst:  "<%= get_var! :'zsh.zlogin_path', type: :file %>"
    only: f?zsh

  - src:  ^(zlogout)$
    dst:  "<%= get_var! :'zsh.zlogout_path', type: :file %>"
    only: f?zsh


# vim: set filetype=eruby.yaml :
